### ISSUE TITLE
drive.mkdir() doesn't create directory

### ISSUE THREAD

**Issue by bjin9** [RangerMauve/hyper-sdk#92]
I am trying to create a directory on a drive.
But it creates a file with the same name, instead of a directory.

` await drive.mkdir(path)`

tested on MacOS Catalina, node v14

**Comment by RangerMauve** [comment]
Thank you for the heads up.

Do you think you could put together a minimal test case that demonstrates this bug?

Maybe even add a [unit test](https://github.com/datproject/sdk/blob/master/test/test.js) so that we can make sure it's fixed in the future.

**Comment by RangerMauve** [comment]
New version of hyper-sdk should change this. Please reopen if you're still facing this error.
